// Generated by ReScript, PLEASE EDIT WITH CARE

import * as School from "./School.bs.js";

console.log("Hello, World!");

console.log("123");

var me3 = {
  age: 36,
  name: "Big ReScript"
};

var me4 = {
  name: "str",
  age: 11
};

me4.age = 22;

console.log(20);

console.log(36);

console.log(me4.age);

var me6 = {
  age: 5,
  name: "Big ReScript"
};

var cc = "lllooo"[-1];

var me7 = {
  age: cc,
  name: "Big ReScript"
};

console.log(cc);

var me = {
  age: 5,
  name: "Big ReScript"
};

var me2 = {
  age: 20,
  name: "Big ReScript"
};

var areYouCrushingIt = /* Yes */0;

var personHasACar = true;

var licenseNumber = 5;

var outModule = School.test;

export {
  me ,
  me2 ,
  me3 ,
  me4 ,
  me6 ,
  areYouCrushingIt ,
  personHasACar ,
  licenseNumber ,
  cc ,
  me7 ,
  outModule ,
}
/*  Not a pure module */
